torchrun --nproc_per_node=4 --nnode=1 src/run_vision_encoder.py \
    --output_dir saves/google_siglip-base-patch16-224_phobert_syllable_base_512_image_27M_all \
    --model_name_or_path models/google_siglip-base-patch16-224_phobert_syllable_base_512 \
    --freeze_vision_model=True \
    --dataset_name image_27M \
    --dataset_config_name all \
    --image_data_dir /lustre/scratch/client/vinai/users/thinhphp1/text2img/vidata/images_27M/ \
    --image_column image \
    --caption_data_dir output/vie_captions/ \
    --caption_column caption \
    --remove_unused_columns=False \
    --selected_indices_file data/tmp/indices/gemini-1.5-flash_caption_indices.json \
    --removed_indices_file data/tmp/indices/invalid_caption_indices.json \
    --custom_order=True \
    --do_train \
    --num_train_epochs 30 \
    --per_device_train_batch_size 512 \
    --gradient_accumulation_steps 1 \
    --enable_gradient_checkpointing=True \
    --optim adamw_hf \
    --learning_rate 1.25e-4 \
    --weight_decay 1e-4 \
    --adam_beta1 0.9 \
    --adam_beta2 0.95 \
    --adam_epsilon 1e-6 \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.1 \
    --dataloader_num_workers 16 \
    --preprocessing_num_workers 16 \
    --dataloader_persistent_workers=True \
    --dataloader_prefetch_factor 4 \
    --logging_first_step=True \
    --logging_steps 268 \
    --save_steps 1339 \
    --use_liger_kernel=True \
    --report_to tensorboard \
    --ddp_timeout 3600 \
    --bf16=True \
    --deepspeed configs/ds_z2_config.json
